# If set to true, JDS require JDC to reveal the transactions they are going to mine on
full_template_mode_required = true

# SRI Pool config
authority_public_key = "9auqWEzQDVyd2oe1JVGFLMLHZtCo2FFqZwtKA5gd9xbuEu7PH72"
authority_secret_key = "mkDLTBBRxdBv998612qipDYoTK3YUrqLe8uWw7gu3iXbSrn2n"
cert_validity_sec = 3600

# Version support
max_supported_version = 2
min_supported_version = 2

# Coinbase outputs are specified as descriptors. A full list of descriptors is available at
#     https://github.com/bitcoin/bips/blob/master/bip-0380.mediawiki#appendix-b-index-of-script-expressions
# Although the `musig` descriptor is not yet supported and the legacy `combo` descriptor never
# will be. If you have an address, embed it in a descriptor like `addr(<address here>)`.
coinbase_reward_script = "addr(tb1q2zc2k3uh6ketqd6yswzdy8evrcvd8yxn4sw0f5)"

# SRI Pool JD config
listen_jd_address = "10.5.0.5:34264"
# RPC config for mempool (it can be also the same TP if correctly configured)
core_rpc_url =  "http://10.5.0.2"
core_rpc_port = 18332
core_rpc_user =  "username"
core_rpc_pass =  "password"
# Time interval used for JDS mempool update 
[mempool_update_interval]
unit = "secs"
value = 1

# Additional v1.5.0 compliance settings
[timeout]
unit = "secs"
value = 30
