# Braiins Pool Upstream Connection
# upstream_authority_pubkey = "u95GEReVMjK6k5YqiSFNqqTnKU4ypU2Wm8awa6tmbmDmk1bWt"
# upstream_address = "18.196.32.109"
# upstream_port = 3336

# Local Mining Device Downstream Connection
downstream_address = "10.5.0.7"
downstream_port = 34256

# Version support
max_supported_version = 2
min_supported_version = 2

# Extranonce2 size for downstream connections
# This controls the rollable part of the extranonce for downstream miners
# Max value for CGminer: 8
# Min value: 2
downstream_extranonce2_size = 4

# User identity/username for pool connection
# This will be appended with a counter for each mining client (e.g., username.miner1, username.miner2)
user_identity = "translator_user"

# Aggregate channels: if true, all miners share one upstream channel; if false, each miner gets its own channel
aggregate_channels = false

# Difficulty params
[downstream_difficulty_config]
# hashes/s of the weakest miner that will be connecting (e.g.: 10 Th/s = 10_000_000_000_000.0)
min_individual_miner_hashrate = 10_000_000_000_000.0
# target number of shares per minute the miner should be sending
shares_per_minute = 6.0
# disable variable difficulty adjustment when using with JDC (JDC handles vardiff)
enable_vardiff = false

[[upstreams]]
address = "10.5.0.17"
port = 34251
authority_pubkey = "9auqWEzQDVyd2oe1JVGFLMLHZtCo2FFqZwtKA5gd9xbuEu7PH72"
